[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]
edition = "2018"

[features]
default = ["gui"]
gui = ["glium"]

[dependencies]
blip_buf = ">=0.1.3"
clap = { version = "2", default_features = false }
cpal = "0.13"
glium = { version = "0.28", optional = true, default_features = false, features = [ "glutin" ] }

[[bin]]
name = "rboy"
test = false
doc = false
