[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]
edition = "2018"

[features]
default = ["gui"]
gui = ["glium"]

[dependencies]
blip_buf = ">=0.1.3"
clap = "4"
cpal = "0.15"
glium = { version = "0.34", optional = true }
winit = "0.29"

[[bin]]
name = "rboy"
test = false
doc = false
